### ISSUE TITLE
Add an option to CLI to directly render templates

### ISSUE THREAD

**Issue by IgnisDa** [zenorocha/react-email#227]
Awesome project!

I would like to import the rendered emails into my rust application, so I can not use the `@react-email/render` utility. It would be great if the CLI had a `email build` option that would build all the components and spit them out to a configurable location.

My current workaround in a custom script.

**Comment by leemeichin** [comment]
Any chance of updating here or syncing Discord to this? I'm interested in this but I don't want to sign up to Discord to understand what's happening

**Comment by bukinoshita** [comment]
@leemeichin We are still investigating how we're going to do this. If you can share your use case, would be really helpful to understand your needs and make sure it works for your case.

**Comment by leemeichin** [comment]
@bukinoshita use-case is that we want to pre-compile email templates in our CI pipeline. 

We're running a Ruby on Rails app that uses its own mailer system, so we wanted to build our layouts in react-email and then export them into the Rails pipeline as templates, where we then interpolate context specific values.

We can't do that, of course, so someone has to manually spin up the react-email dev server and then `view source` in the browser to copy the output and paste it into our layout, and then manually review the result to replace the template variables.

I'd like to ask what you're investigating, because what we're looking at is just writing the email output to a file and not to an API or dev server.
