### ISSUE TITLE
Support `npm` package manager

### ISSUE THREAD

**Issue by bukinoshita** [zenorocha/react-email#246]
We're using `yarn` under the hood. We should check if user has `yarn` or `npm` and use their "preferred" package manager.

Request from Discord: https://discord.com/channels/1022242959736983613/1022244210583277658/1054425989083574302

**Comment by niicojs** [comment]
Thanks bukinoshita!
Just FYI, I just test it and you can use your package manager for your project as long as you have `yarn` installed under the hood.
In my case: 
- I used `pnpm dlx` instead of `npx` to boot the project
- used `pnpm i` to install dependencies on my project
- `npm` to launch it (vscode use it)
